### ISSUE TITLE
Adding color codes to the warp's name breaks the plugin.

### ISSUE THREAD

**Issue by koutsie** [HALD91/Warp#1]
```python
[INFO] .... koutsie issued server command: /warp Mökki
[INFO] .... Incorrect argument for command
[INFO] .... tp koutsie 891.5049471832291 98.0 375.5588218376899<--[HERE]```


f?

**Comment by HALD91** [comment]
Just to make sure i understand you right.. if you do /warp set &6test. i wont let you do /warp test?

**Comment by HALD91** [comment]
I have been testing the telepotion with color codes and if you set a warp with exemple /warp set &6test. you well have to /warp &6test.
You can also do /warp list - to see what your Warp is called or you can look in the Warp Config.

**Comment by koutsie** [comment]
> Just to make sure i understand you right.. if you do /warp set &6test. i wont let you do /warp test?

Exactly, you'd have to also type in the color code.... which doesn't make any sense to end users lolw

**Comment by HALD91** [comment]
Okay I well look at. and try to find a solution.

**Comment by HALD91** [comment]
I wasn't able to fix it so you cloud use color coded warp names so i had to disable so you could set warps with color coded names.
¨
New version:
https://www.spigotmc.org/resources/warp.84315/

**Comment by hypersmc** [comment]
@HALD91 Remember to close issues after they have been fixed.
